name: iris-classification
channels:
  - conda-forge
dependencies:
  - python=3.8
  - fastapi=0.95.0
  - uvicorn
  - scikit-learn=1.0.2
  - pandas
  - numpy
  - joblib
  - pydantic
  - pytest  
  - pip
  - pip:
    - ucimlrepo  
    - matplotlib  
    - seaborn     
